ALTER TABLE character ADD COLUMN head_item TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE character ADD COLUMN beard_item TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE character ADD COLUMN hands_item TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE character ADD COLUMN legs_item TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE character ADD COLUMN feet_item TEXT NOT NULL DEFAULT 'NONE';
